spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: dev # 현재 활성화할 프로파일
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT}


# 로깅 레벨 설정
logging:
  level:
    com.card.payment: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:172.30.1.33}